name: Issue Default
description: Use this template for creating new issues
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to properly describe the new issue.
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: A clear and concise description of the issue.
    validations:
      required: true
  - type: textarea
    id: recommend
    attributes:
      label: Recommend
      placeholder: |-
        -
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots (if appropriate)
      description: If applicable, add screenshots to help explain your problem.
  - type: textarea
    id: checklist
    attributes:
      label: Checklist (if needed)
      placeholder: |-
        - [ ]
  - type: textarea
    id: extend-content
    attributes:
      label: Additional context
      description: Add any other context about the pull request here.
