import type { Metadata } from 'next';
import '@/assets/styles/globals.css';
import { Airbnb } from '@/lib/fontsLocal';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${Airbnb.variable}`}>{children}</body>
    </html>
  );
}
